# Generated by Django 3.0.6 on 2020-05-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upVote',
            field=models.IntegerField(null=True),
        ),
    ]
